PR Final SPRINT 1
memezinga/memezinga pull request #19
Opened 2019-02-05 13:51 UTC by KoolTheba

Please Review @UlisesGascon !

2019-02-05 15:15 UTC, UlisesGascon requested changes
# Sprint Review

**General**
- En general ha sido un gran trabajo! El equipo esta empezando el rodaje y se nota, pero podeis estar muy orgullosas del trabajo realizado :sunglasses:
- Para el próximo sprint debemos tener claro el esquema de trabajo en ramas de GIT, es dificil seguir todos los cambios con los commits que tenemos.
- Gracias por referenciar los issues en la mayoría de los commits :+1:
- Bravo por usar un Yeoman, gulp, babel y todo el entorno! :clap::clap:
- Me gusta muchisimo el nuevo diseño y los mocks se aproximan bastante aunque quedan algunos detalles menores...
- Gracias por actualizar el `README.md` en este sprint
- Estupendo trabajo en el responsive! :clap::clap::clap:
- Faltan los diseños por subirse


**Cosas para el próximo sprint**
- Es importante incluir en el `README.md` como manejar el proyecto a nivel de tareas de Gulp y demás...
- Igual podríamos incluir metadatos en el HTML para compartir en redes sociales
- Añadimos [`humans.txt`](http://humanstxt.org/ES)?
- Tabular bien automaticamente el sass
- Voto por hacer un refactor antes de hacer el PR

### Bugs
- Falta el efecto "descuadre" en la galería
- Faltan las bolitas de pasos en algunas vistas...
- Alineación de elementos
![captura de pantalla 2019-02-05 a las 16 10 05](https://user-images.githubusercontent.com/5110813/52282365-8d8df200-2960-11e9-8255-2951c76f8328.png)

2019-02-05 15:15 UTC, UlisesGascon commented on README.md
> +![screenshot](other/memezinga-screenshot.png)
Bien Jugado! Mola poder previsualizar :-)

2019-02-05 15:15 UTC, UlisesGascon commented on README.md
> +- Yeomann and Gulp has been used
Metería un poco más de detalle

2019-02-05 15:15 UTC, UlisesGascon commented on README.md
> +### Contributors:
Es interesante explicar los roles de cada una también

2019-02-05 15:15 UTC, UlisesGascon commented on app/scripts/main.js
> +console.log("'Allo 'Allo!");
Yo esperaba algo más... `Hello Memezinga!`

2019-02-05 15:15 UTC, UlisesGascon commented on app/scripts/main.js
> +$(window).scroll(function(){
Voto por migrarlo a JS.. y dejar JQuery atras... aunque sea una dependencia de Bootstrap

2019-02-05 15:15 UTC, UlisesGascon commented on package.json
> +  "dependencies": {
Sería interesante anclar las versiones de las dependencias para evitar sustos en el futuro

2019-02-05 15:15 UTC, UlisesGascon commented on package.json
> +  "browserslist": [
Faltan autor y contributors...

2019-02-05 15:15 UTC, UlisesGascon commented on app/index.html
> +      <link rel="apple-touch-icon" href="apple-touch-icon.png">
No es nuestro logo...

2019-02-05 15:15 UTC, UlisesGascon commented on app/index.html
> +         <button type="button" class="btn btn-outline-light"><i class="fas fa-user"></i>LOGIN</button>
Las mayúsculas pueden ir por CSS...

2019-02-05 15:15 UTC, UlisesGascon commented on app/index.html
> +<html lang="">
no esta completado :-(

2019-02-05 15:15 UTC, UlisesGascon commented on app/index.html
> +      <meta charset="UTF-8">
meta description? Dónde esta?

2019-02-05 15:15 UTC, UlisesGascon commented on app/step3.html
> +      <script src="Firebase/firebase.js"></script>
No entiendo porque usamos `Firebase` y no `scripts` para esto

2019-02-05 15:15 UTC, UlisesGascon commented on app/Firebase/firebase.js
> +const firebase = require('firebase-admin');
Esto no va asi en Web....

El esquema suele ser... [Referencia](https://firebase.google.com/docs/web/setup)
```html
<script src="https://www.gstatic.com/firebasejs/5.5.2/firebase.js"></script>
<script>
  // Initialize Firebase
  // TODO: Replace with your project's customized code snippet
  var config = {
    apiKey: "<API_KEY>",
    authDomain: "<PROJECT_ID>.firebaseapp.com",
    databaseURL: "https://<DATABASE_NAME>.firebaseio.com",
    projectId: "<PROJECT_ID>",
    storageBucket: "<BUCKET>.appspot.com",
    messagingSenderId: "<SENDER_ID>",
  };
  firebase.initializeApp(config);
</script>
```

2019-02-05 15:15 UTC, UlisesGascon commented on app/styles/main.scss
> +  background:#000;
mejor en variable de color...

2019-02-05 15:15 UTC, UlisesGascon commented on app/styles/main.scss
> +@media screen and (max-width: 575.98px){
variable es mucho más eficiente para luego poder reutilizarlo

2019-02-05 15:15 UTC, UlisesGascon commented on app/styles/main.scss
> +	width: 80%;
Mala tabulación!

2019-02-05 15:15 UTC, UlisesGascon commented on app/styles/main.scss
> +	width: 85%;
mala tabulación

2019-02-05 15:15 UTC, UlisesGascon commented on app/styles/main.scss
> +.footer-flexObj {
`flexObj`? No es muy descriptivo

2019-02-08 19:03 UTC, Fa-v commented on app/Firebase/firebase.js
> +const firebase = require('firebase-admin');
Había seguido el esquema para node 🙊
done!

2019-02-08 19:06 UTC, Fa-v commented
Si podemos revisar el lunes el esquema de las ramas de Git sería genial 😄

2019-02-09 16:05 UTC, UlisesGascon approved these changes

2019-02-09 16:06 UTC, UlisesGascon commented
Gran trabajo con los cambios @Fa-v y @KoolTheba! 👏👏👏

2019-02-09 16:06 UTC, merged